SET C51INC=D:\Program Files\keil\C51\INC\Evatronix\;D:\Program Files\keil\C51\INC\
SET C51LIB=D:\Program Files\keil\C51\LIB
SET CPU_TYPE=R8051XC (1 DPTR)
SET CPU_VENDOR=Evatronix
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"D:\Program Files\keil\C51\BIN\A51.EXE" @STARTUP._ia
"D:\Program Files\keil\C51\BIN\C51.EXE" @.\shark.__i
"D:\Program Files\keil\C51\BIN\BL51.EXE" @shark.lnp
"D:\Program Files\keil\C51\BIN\OH51.EXE" "shark" 
D:\Project\windows_app\project-ydxit_3_2_2\branch\proj\Bulid.bat
